#!/bin/bash

SAMPLES=./samples
CACHE=./build/checker

mkdir -p ${CACHE}

for url in `cat "${SAMPLES}"  | grep '.' | sort | uniq | shuf`; 
do  
    #echo ${url}
    if [[ "${url}" =~ \?verb ]]; then
        BASEURL=`echo ${url} | sed 's|\?verb.*||'`
    else
        BASEURL=${url}
    fi	
    #echo BASEURL=${BASEURL}

    OUTFILE=`mktemp ${CACHE}/out.XXXXXXX` || die "cannot create OUTFILE"

    IdentifyURL="${BASEURL}?verb=Identify"
    wget "${IdentifyURL}" -e robots=off --no-check-certificate --output-document=${OUTFILE}
    echo return value $?
    


    ListSetsURL="${BASEURL}?verb=ListSets"
    ListMetadataFormatsURL="${BASEURL}?verb=ListMetadataFormats"
    echo IdentifyURL=${IdentifyURL}

    

done

